version: '3.9'

services:
  grayscale:
    build:
      context: ./services
      dockerfile: grayscale_service/Dockerfile
    ports:
      - '8001:8001'
    volumes:
      - ./storage:/app/storage

  resize:
    build:
      context: ./services
      dockerfile: resize_service/Dockerfile
    ports:
      - '8002:8002'
    volumes:
      - ./storage:/app/storage

  nginx:
    image: nginx:latest
    ports:
      - '80:80'
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
      - ./frontend:/usr/share/nginx/html:ro # Add this line for frontend
      - ./storage:/storage
    depends_on:
      - resize
      - grayscale
      - frontend # Add this line for frontend

  # Add this new service for development (optional)
  frontend:
    build:
      context: ./services
      dockerfile: frontend/Dockerfile
    working_dir: /app
    ports:
      - '3000:3000'
