version: '3.9'

services:
  grayscale:
    build:
      context: ./services
      dockerfile: grayscale_service/Dockerfile
    ports:
      - '8001:8001'
    volumes:
      - ./storage:/app/storage

  resize:
    build:
      context: ./services
      dockerfile: resize_service/Dockerfile
    ports:
      - '8002:8002'
    volumes:
      - ./storage:/app/storage

  view:
    build:
      context: ./services
      dockerfile: view_service/Dockerfile
    ports:
      - '8003:8003'
    volumes:
      - ./storage:/app/storage

  nginx:
    image: nginx:latest
    ports:
      - '80:80'
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
      - ./frontend:/usr/share/nginx/html:ro # Add this line for frontend
    depends_on:
      - resize
      - grayscale
      - view

  # Add this new service for development (optional)
  frontend:
    image: node:16
    working_dir: /app
    volumes:
      - ./frontend:/app
    ports:
      - '3000:3000'
    command: sh -c "npm install -g live-server && live-server --port=3000"
    depends_on:
      - nginx
