version: '3.9'
services:
  grayscale:
    image: sudhanshu177/image-processing-grayscale
    ports:
      - '8001:8001'
    volumes:
      - ./storage:/app/storage

  resize:
    image: sudhanshu177/image-processing-resize
    ports:
      - '8002:8002'
    volumes:
      - ./storage:/app/storage
  nginx:
    image: nginx:latest
    ports:
      - '80:80'
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
      - ./frontend:/usr/share/nginx/html:ro # Add this line for frontend
      - ./storage:/storage
    depends_on:
      - resize
      - grayscale
      - frontend # Add this line for frontend

  frontend:
    image: sudhanshu177/image-processing-frontend
    ports:
      - '3000:3000'
