apiVersion: v1
kind: ConfigMap
metadata:
  name: nginx-config
data:
  nginx.conf: |
    events { }

    http {
      client_max_body_size 10M;
      
      

      server {
        listen 80;

        location / {
          proxy_pass http://frontend:3000;
          proxy_connect_timeout 60s;
          proxy_send_timeout 60s;
          proxy_read_timeout 60s;
        }

        location /api/resize {
          proxy_pass http://resize/resize/;
          proxy_connect_timeout 60s;
          proxy_send_timeout 60s;
          proxy_read_timeout 60s;
        }

        location /api/grayscale {
          proxy_pass http://grayscale/grayscale/;
          proxy_connect_timeout 60s;
          proxy_send_timeout 60s;
          proxy_read_timeout 60s;
        }

        location ~ ^/storage/(.*)$ {
          alias /storage/$1;
        }
      }
    }
