apiVersion: v1
kind: ConfigMap
metadata:
  name: nginx-config
data:
  nginx.conf: |
    events { }

    http {
      client_max_body_size 10M;
      
      

      server {
        listen 80;
        
        
          # Add these routes
        location /api/grayscale/health {
            proxy_pass http://grayscale/health;
        }

        location /api/resize/health {
            proxy_pass http://resize/health;
        }

        # Add a general health endpoint for the gateway itself
        location /health {
            access_log off;
            return 200 '{"status":"healthy","service":"nginx"}';
            default_type application/json;
        }

        location / {
          proxy_pass http://frontend:3000;
          proxy_connect_timeout 60s;
          proxy_send_timeout 60s;
          proxy_read_timeout 60s;
        }

        location /api/resize {
          proxy_pass http://resize/resize/;
          proxy_connect_timeout 60s;
          proxy_send_timeout 60s;
          proxy_read_timeout 60s;
        }

        location /api/grayscale {
          proxy_pass http://grayscale/grayscale/;
          proxy_connect_timeout 60s;
          proxy_send_timeout 60s;
          proxy_read_timeout 60s;
        }

        location ~ ^/storage/(.*)$ {
          alias /storage/$1;
        }
      }
    }
